services:
  - type: web
    name: image-processor-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1 