services:
  - type: web
    name: image-processor-api
    env: node
    buildCommand: |
      npm install
      pip install -r requirements.txt
      cp test.html /opt/render/project/src/
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: uploads
      mountPath: /tmp
      sizeGB: 1
    runtime: python3
    staticPublishPath: ./ 