services:
  - type: web
    name: image-processor-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=450"
      - key: REMBG_MAX_MEMORY
        value: "450"
    disk:
      name: uploads
      mountPath: /tmp
      sizeGB: 1
    runtime: python3
    staticPublishPath: ./
    plan: standard
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      cpu: 1
      memory: 2048
      swap: 2048 