services:
  - type: web
    name: image-processor-api
    env: node
    buildCommand: |
      npm install
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p /tmp/uploads /tmp/processed
      chmod 777 /tmp/uploads /tmp/processed
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: uploads
      mountPath: /tmp
      sizeGB: 1
    runtime: python3
    staticPublishPath: ./ 