services:
  - type: web
    name: image-processor-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PATH
        value: /opt/render/project/python/bin:${PATH}
    disk:
      name: uploads
      mountPath: /tmp
      sizeGB: 1
    runtime: python3
    staticPublishPath: ./ 